# all the configurations for the projec
# want to store favorite editor, language extensions, favorite language

favEditor: 'vim'
favExtension: 'cpp'
favBrowser: 'firefox'
handle: 'itspax'
maxCalls: 10
compiles:
    cpp: True
    python: False
    java: True
compileCmd:
    cpp: "'g++', contestNo+problemAlpha+'.cpp', '-o', contestNo+problemAlpha"
