# all the configurations for the projec
# want to store favorite editor, language extensions, favorite language

favEditor: 'vim'
favExtension: 'cpp'
favBrowser: 'firefox'
handle: 'itspax'
maxCalls: 10
compiles:
    cpp: True
    python: False
    java: True
keys:
    up: 'k'
    rskip: 'r'
    lskip: 'e'
    down: 'j'
    attempt: 'i'
    update: 'u'
    close: 'c'
    searchName: 'n'
    searchIdInd: 's'

